# Generated by Django 6.0.2 on 2026-03-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userprofile_avatar_url_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(blank=True, default='', help_text='Display username chosen at registration.', max_length=50),
        ),
    ]
